apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  template:
    spec:
      containers:
        - name: openldap
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: yes
            - name: LDAP_ENABLE_TLS
              value: yes
            - name: LDAP_TLS_CERT_FILE
              value: /opt/bitnami/openldap/certs/tls.crt
            - name: LDAP_TLS_KEY_FILE
              value: /opt/bitnami/openldap/certs/tls.key
            - name: LDAP_TLS_CA_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          volumeMounts:
            - name: certs
              mountPath: /opt/bitnami/openldap/certs/tls.crt
              subPath: tls.crt
            - name: certs
              mountPath: /opt/bitnami/openldap/certs/tls.key
              subPath: tls.key
      volumes:
        - name: certs
          secret:
            secretName: openldap-serving-cert
            defaultMode: 440
