apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-network
  namespace: aaa
spec:
  config: |2
    {
            "cniVersion": "0.3.1", 
            "name": "localnet2", 
            "type": "ovn-k8s-cni-overlay", 
            "topology": "localnet", 
            "netAttachDefName": "aaa/localnet-network"
    }
