apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-ens19
spec:
  desiredState:
    interfaces:
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: ens19
            - name: ovs-br1
        description: |-
          A dedicated OVS bridge with ens119 as a port
          allowing all VLANs and untagged traffic
        name: ovs-br1
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: ovs-br1
          localnet: localnet2
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ''
