apiVersion: v1
kind: Secret
metadata:
  name: repo-os-tools
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: default
  url: https://github.com/aushacker/os-tools.git
