apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec
  labels:
    app.kubernetes.io/name: sec-root
spec:
  selector:
    matchLabels:
      app: sec-root
  template:
    metadata:
      labels:
        app: sec-root
    spec:
      serviceAccountName: sa-sec-root
      containers:
        - name: main
          securityContext:
            runAsUser: 0
            privileged: false
            allowPrivilegeEscalation: true
