kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-anyuid
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
    verbs:
      - use
