apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-redis.yaml
  - service-redis.yaml
  - secret-redis.yaml
  - statefulset-db.yaml
  - service-db.yaml
  - secret-db.yaml
  - configmap-quay.yaml
  - statefulset-quay.yaml
  - service-quay.yaml

images:
  - name: postgresql
    newName: registry.redhat.io/rhel8/postgresql-13
    newTag: '1-169.1708918658'
  - name: quay
    newName: registry.redhat.io/quay/quay-rhel8
    newTag: 'v3.10.4-5'
  - name: redis
    newName: registry.redhat.io/rhel8/redis-6
    newTag: '1-170'
  - name: ubi8
    newName: registry.access.redhat.com/ubi8
    newTag: '8.9-1136'
