kind: Secret
apiVersion: v1
metadata:
  name: database-credentials
stringData:
  POSTGRESQL_USER: quayuser
  POSTGRESQL_PASSWORD: quaypass
  POSTGRESQL_DATABASE: quay
  POSTGRESQL_ADMIN_PASSWORD: adminpass 
type: Opaque
