apiVersion: v1
kind: Service
metadata:
  name: quay
spec:
  selector:
    app: quay
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
