kind: Secret 
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
stringData:
  external_cluster_details:
    {{ required "The external ceph cluster JSON data must be supplied" .Values.externalCluster.details }}
type: Opaque
