kind: Secret 
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  external_cluster_details:
    {{ required "The external ceph cluster JSON data must be supplied" .Values.externalCluster.details | toJson | b64enc }}
type: Opaque
