apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: external
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  externalStorage:
    enable: true
  labelSelector: {}
