apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  labels:
    operators.coreos.com/odf-operator.openshift-storage: ""
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: odf-operator
  source: {{ .Values.subscription.source }}
  sourceNamespace: openshift-marketplace
