---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-s3.yaml
  - lokistack.yaml
  - serviceaccount.yaml

patches:
  - path: subscription-patch.yaml
