---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-s3.yaml
  - lokistack.yaml

components:
  - ../../components/v6.1
  - ../../components/v6.x-rbac-base
