apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: local-hdd
        default: true
        deviceSelector:
          paths:
            - /dev/disk/by-path/pci-0000:01:02.0-scsi-0:0:0:1
        fstype: xfs
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
      - name: local-ssd
        deviceSelector:
          paths:
            - /dev/disk/by-path/pci-0000:01:03.0-scsi-0:0:0:2
        fstype: xfs
        thinPoolConfig:
          name: thin-pool-2
          overprovisionRatio: 10
          sizePercent: 90
