apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: foo
  namespace: policies
  labels:
    app: infra
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions: []
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
