kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: example.com/mirror/oc-mirror-metadata
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.14
      minVersion: 4.14.27
      maxVersion: 4.14.28
      shortestPath: true
      type: ocp
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: lvms-operator
      channels:
      - name: stable-4.14
    - name: cluster-logging
      channels:
      - name: stable-5.9
    - name: compliance-operator
      channels:
      - name: stable
    - name: redhat-oadp-operator
      channels:
      - name: stable-1.3
    - name: openshift-cert-manager-operator
      channels:
      - name: stable-v1
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: rhacs-operator
      channels:
      - name: stable
    - name: cincinnati-operator
      channels:
      - name: v1
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.14
    packages:
    - name: external-secrets-operator
      channels:
      - name: stable
  additionalImages:
  - name: registry.redhat.io/ubi9/ubi:latest
  helm: {}
