apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-app-policies
policyDefaults:
  namespace: policies
  remediationAction: enforce
policies:
  - name: app-nginx
    manifests:
      - path: nginx/namespace.yaml
      - path: nginx/cm-static-content.yaml
      - path: nginx/deployment.yaml
      - path: nginx/service.yaml
      - path: nginx/route.yaml
