apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - rb-anyuid.yaml
  - serviceaccount.yaml
  - service.yaml

configMapGenerator:
- name: rsyslog-config
  files:
    - rsyslog.conf
  options:
    disableNameSuffixHash: true
