apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
- name: rsyslog-config
  files:
    - rsyslog.conf
  options:
    disableNameSuffixHash: true
