kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rsyslog-scc-anyuid
subjects:
  - kind: ServiceAccount
    name: rsyslog
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-anyuid
