apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: generic-build
spec:
  params:
    - name: git-url
      description: Repository URL to clone from
      type: string
    - name: git-revision
      default: main
      description: Revision to checkout (branch, tag, sha, ref etc.)
      type: string
    - name: context-dir
      type: string
      description: The context directory within the repository for sources on which we want to execute maven goals
      default: '.'
    - name: image
      type: string
      description: The name (reference) of the image to build.
      default: ""
  tasks:
    - name: fetch
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        resolver: hub
        params:
          - name: type
            value: tekton
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: version
            value: "0.7"
      runAfter:
        - fetch
      params:
        - name: CONTEXT
          value: $(params.context-dir)
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: dockerconfig
  workspaces:
    - name: source
    - name: dockerconfig
