apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
data:
  init-mongo.js: |
    db.getSiblingDB('admin').auth(
      process.env.MONGODB_INITDB_ROOT_USERNAME,
      process.env.MONGODB_INITDB_ROOT_PASSWORD
    );
    db.createUser({
      user: process.env.MONGODB_USER,
      pwd: process.env.MONGODB_PASSWORD,
      roles: ["readWrite"],
    });
