apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"mongodb"}]'
  labels:
    app.kubernetes.io/name: graylog
    app.kubernetes.io/part-of: graylog
    app.kubernetes.io/component: ui
    app.openshift.io/runtime: java
spec:
  selector:
    matchLabels:
      app: graylog
  replicas: 1
  template:
    metadata:
      annotations:
        openshift.io/required-scc: nonroot-v2
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: GRAYLOG_NODE_ID_FILE
              value: "/usr/share/graylog/data/data/node-id"
            - name: GRAYLOG_PASSWORD_SECRET
              valueFrom:
                secretKeyRef:
                  name: graylog-credentials
                  key: password
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              valueFrom:
                secretKeyRef:
                  name: graylog-credentials
                  key: passwordSha
            - name: GRAYLOG_HTTP_BIND_ADDRESS
              value: "0.0.0.0:9000"
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: "http://graylog-graylog.apps.sno.home.lab/"
            - name: GRAYLOG_MONGODB_URI
              value: "mongodb://graylog:password@mongodb:27017/graylog"
            - name: GRAYLOG_REPORT_DISABLE_SANDBOX
              value: "true"
          ports:
            - containerPort: 5044  # Beats
            - containerPort: 5140  # Syslog TCP
            - containerPort: 5140  # Syslog UDP
              protocol: UDP
            - containerPort: 5555  # RAW TCP
            - containerPort: 5555  # RAW UDP
              protocol: UDP
            - name: http           # Server API
              containerPort: 9000
            - containerPort: 12201 # GELF TCP
            - containerPort: 12201 # GELF UDP
              protocol: UDP
            - containerPort: 13301 # Forwarder data
            - containerPort: 13302 # Forwarder config
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
#          livenessProbe:
#            httpGet:
#              path: /index.html
#              port: 8080
#              initialDelaySeconds: 3
#              periodSeconds: 3
#          readinessProbe:
#            httpGet:
#              path: /index.html
#              port: 8080
#              initialDelaySeconds: 3
#              periodSeconds: 3
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsUser: 1100
        runAsGroup: 1100
      serviceAccountName: graylog
