kind: Secret
apiVersion: v1
metadata:
  name: graylog-credentials
stringData:
  # Only for testing
  password: Z8xqlG6LzIJzUnLR9ZriQmGAFOnVntyrXs8PtvYqCE-xU6Swb8zWhP7ZbNV9Kn2Wtogr2lxUI-txa-Wp0xffn1OUSoexY5gL
  passwordSha: 617136d92849c6670f04f15cad859c5a4d6d4b06e8f36b0b43a08575e6592c0a
type: Opaque
