apiVersion: v1
kind: Service
metadata:
  name: graylog
spec:
  selector:
    app: graylog
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: syslog-tcp
      port: 5140
      targetPort: 5140
    - name: syslog-udp
      port: 5140
      targetPort: 5140
      protocol: UDP
