apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-management
  namespace: openshift-gitops
spec:
  destination:
    namespace: advanced-cluster-management
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: day2/acm/overlays/v2.12
    repoURL: 'https://github.com/aushacker/os-tools.git'
    targetRevision: HEAD
