apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openldap

resources:
  - ../../base

images:
- name: openldap
  newName: docker.io/bitnami/openldap
  newTag: latest

#patches:
#- path: patch-deployment-ports.yaml
