apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

images:
- name: openldap
  newName: docker.io/bitnami/openldap
  newTag: latest
