apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-ns

nameSuffix: -dev

resources:
  - namespace.yaml
  - cm-example1.yaml
  - cm-example2.yaml

replacements:
  - path: replace1.yaml
#  - path: replace2.yaml
