apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/standard-labels
  - ../../components/icons
  - ../../components/connections
