apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: azure-key-example
spec:
  externalSecretSpec:
    data:
      - remoteRef:
          key: key/Key01
        secretKey: key
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: replaceMe
    target:
      name: patchMe
      template:
        data:
          public: '{{ .key | jwkPublicKeyPem }}'
        engineVersion: v2
        type: Opaque      
  namespaceSelector:
    matchLabels:
      environment: dev
  refreshTime: 1m
