---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: mydb
  namespace: default
spec:
  characterSet: utf8
  collate: utf8_general_ci
  mariaDbRef:
    name: mariadb
    waitForIt: true
  retryInterval: 5s
