---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: myuser
  namespace: default
spec:
  host: '%'
  mariaDbRef:
    name: mariadb
    waitForIt: true
  maxUserConnections: 20
  passwordSecretKeyRef:
    key: password
    name: mariadb-password
  retryInterval: 5s
