FROM registry.access.redhat.com/ubi9-minimal@sha256:b6ec3ea97ba321c7529b81ae45c407ba8039d52fea3f7b6853734d7f8863344b

COPY ./mongodb-org-7.0.repo /etc/yum.repos.d/mongodb-org-7.0.repo

RUN microdnf install -y mongodb-mongosh-shared-openssl3 && \
    microdnf clean all

WORKDIR /work

RUN chmod g+rwx /work

ENTRYPOINT ["sleep", "infinity"]
