apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  labels:
    app.kubernetes.io/name: my-api
    app.kubernetes.io/instance: my-api
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ocp-apps-demo
    app.openshift.io/runtime: nodejs
  annotations:
    app.openshift.io/connects-to: my-db
spec:
  selector:
    matchLabels:
      app: my-api
  replicas: 1
  template:
    metadata:
      labels:
        app: my-api
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: my-api
          image: registry.access.redhat.com/ubi9/ubi-micro
          command: ['sh', '-c', 'while true; do echo "tick" && sleep 60; done']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
