apiVersion: v1
kind: Service
metadata:
  name: my-api
  labels:
    app.kubernetes.io/name: my-api
    app.kubernetes.io/instance: my-api
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: ocp-apps-demo
spec:
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

