apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: graylog

resources:
  - ../../base

images:
  - name: mongodb
    newName: mongodb/mongodb-community-server
    newTag: latest
