apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: graylog

resources:
  - ../../base

images:
  - name: graylog
    newName: docker.io/graylog/graylog
    newTag: '6.1'
  - name: graylog-datanode
    newName: docker.io/graylog/graylog-datanode
    newTag: '6.1'
  - name: mongodb
    newName: docker.io/mongodb/mongodb-community-server
    newTag: latest
