apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-catalog
    app.kubernetes.io/version: '1.25.4'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: catalog
