apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lvm-storage
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-storage
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: day2/lvm-storage/overlays/sno
    repoURL: 'https://github.com/aushacker/os-tools.git'
    targetRevision: HEAD
