kind: Deployment
apiVersion: apps/v1
metadata:
  name: network-tools
  labels:
    app.kubernetes.io/name: network-tools
    app.kubernetes.io/part-of: os-tools
    app.kubernetes.io/component: utility
    app.openshift.io/runtime: redhat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
        - name: tools
          image: registry.redhat.io/openshift4/network-tools-rhel8
          command:
            - /bin/bash
          args:
            - '-c'
            - sleep infinity
          imagePullPolicy: Always
      restartPolicy: Always
