apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
#    metadata:
#      annotations:
#        openshift.io/required-scc: anyuid
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
