apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-infra-policies
placementBindingDefaults:
  name: placement-binding
policyDefaults:
  namespace: policies
  remediationAction: enforce
  placement:
    #placementPath: ../placements/place-foo.yaml # includes manifest (i.e. copies)
    placementName: dev-clusters                 # no Placement generated, must already exist
policies:
#  - name: environment-config
#    manifests:
#      - path: config/dev/
#    policySets:
#      - dev
  - name: infra-logging
    disabled: false
    manifests:
      - path: logging/
    policySets:
      - default
#  - name: infra-oauth-ldap
#    disabled: true
#    manifests:
#      - path: ldap/
#    policySets:
#      - dev
#      - prod
policySets:
  # All clusters
  - name: global
    placement:
      placementName: global-clusters
  - name: default
    placement:
      placementName: default-clusters
  - name: dev
    placement:
      placementName: dev-clusters
  - name: hub
    placement:
      placementName: hub-clusters
  - name: prod
    placement:
      placementName: prod-clusters
