apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-infra-policies
policyDefaults:
  namespace: policies
  remediationAction: enforce
  placement:
    #placementPath: ../placements/place-foo.yaml # includes manifest (i.e. copies)
    placementName: dev-clusters                 # no Placement generated, must already exist
policySetDefaults:
  generatePolicySetPlacement: false
policies:
  - name: environment-config
    manifests:
      - path: config/dev/cm-environment.yaml
    policySets:
      - dev
  - name: infra-oauth-ldap
    disabled: true
    manifests:
      - path: ldap/cm-ldap-ca.yaml
      - path: ldap/secret-bind-password.yaml
      - path: ldap/oauth-patch.yaml
    policySets:
      - dev
      - prod
policySets:
  - name: all
    placement:
      placementName: global-clusters
  - name: dev
    placement:
      placementName: dev-clusters
  - name: prod
    placement:
      placementName: prod-clusters
