apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-infra-policies
policyDefaults:
  namespace: policies
  remediationAction: enforce
  placement:
    placementPath: ../placements/place-foo.yaml # includes manifest (i.e. copies)
    #placementName: foo                          # no Placement
policySetDefaults:
  generatePolicySetPlacement: false
policies:
  - name: infra-oauth-ldap
    manifests:
      - path: ldap/cm-ldap-ca.yaml
      - path: ldap/secret-bind-password.yaml
      - path: ldap/oauth-patch.yaml
