kind: CronJob
apiVersion: batch/v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-group-sync
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 1800
      template:
        spec:
          containers:
            - name: ldap-group-sync
              image: registry.redhat.io/openshift4/ose-cli:latest
              command:
                - /bin/bash
                - -c
                - oc adm groups sync --sync-config=/etc/config/sync.yaml --confirm -v 1
              volumeMounts:
                - mountPath: /etc/config
                  name: ldap-sync-config
                - mountPath: /etc/secrets
                  name: ldap-bind-password
                - mountPath: /etc/ldap-ca
                  name: ldap-ca
          volumes:
            - name: ldap-sync-config
              configMap:
                name: ldap-sync-config
            - name: ldap-bind-password
              secret:
                secretName: ldap-bind-password
            - name: ldap-ca
              configMap:
                name: ca-config-map
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 500
          dnsPolicy: ClusterFirst
          serviceAccountName: ldap-group-syncer
