apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"my-api1"},{"apiVersion":"apps/v1","kind":"Deployment","name":"my-api2"}]'