---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  ingress:
    className: openshift-default
  hostname:
    hostname: sso.apps.sosno.home.lab
  proxy:
    headers: xforwarded
