apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 97-iscsi-master
spec:
  config:
    ignition: 
      version: 3.2.0
    systemd:
      units:
      - name: iscsid.service
        enabled: true
