apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world
spec:
  schedule: "CRON_TZ=Australia/Sydney */1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: quay.io/prometheus/busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello world!
          restartPolicy: OnFailure
