apiVersion: batch/v1
kind: Job
metadata:
  name: print-env
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: quay.io/prometheus/busybox
        command:
        - /bin/sh
        - -c
        - env
      restartPolicy: Never
