#
# Dump Pod environment variables.
# Useful for learning about injected values like Services.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: print-env
spec:
  template:
    spec:
      containers:
      - name: print-env
        image: quay.io/prometheus/busybox
        command:
        - /bin/sh
        - -c
        - env
      restartPolicy: Never
