apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: os-tools-git
  namespace: default
spec:
  type: git
  params:
  - name: url
    value: https://github.com/aushacker/os-tools.git
  - name: revision
    value: master
#  - name: httpsProxy
#    value: "my.proxy.com"

