---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: infra-policies
placementBindingDefaults:
  name: infra-binding
policyDefaults:
  namespace: policies
  remediationAction: enforce
  placement:
    placementName: openshift-clusters                 # no Placement generated, must already exist
  policySets:
    - day2-operators

policies:
  - name: authentication-htpasswd
    description: |
      Configures the cluster OAuth resource to use an HTpasswd identity provider.
    manifests:
      - path: oauth/

  - name: openshift-logging-install
    description: |
      Installs the openshift-logging operator.
    manifests:
      - path: logging/operator/
 
  - name: openshift-logging-configuration
    description: |
      Configures the openshift-logging operator.
    manifests:
      - path: logging/instance/
    dependencies:
      - name: openshift-logging-install
 
policySets:
  - name: day2-operators
    placement:
      placementName: openshift-clusters
