FROM docker.io/library/alpine:3.20

RUN apk add gcc-avr avr-libc make && \
    apk cache clean

# Copy downloaded .atpack files into container
COPY *.atpack /tmp

# Extract downloaded files
RUN mkdir /atpack && \
    cd /tmp && \
    for f in *.atpack; do unzip -n -d /atpack $f; done

RUN mkdir /work
WORKDIR /work

USER 1000

ENTRYPOINT [ "make" ]
CMD [ "all" ]
