apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-failed
spec:
  lookupPolicy:
    local: true
  tags:
  - name: {{ .Values.image.tag | default .Chart.AppVersion }}
    from:
      kind: DockerImage
      name: {{ .Values.image.repository }}
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Local
