apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nexus
  resources:
    requests:
      storage: 5Gi
