apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet1
  namespace: aaa
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "localnet1",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "physicalNetworkName": "localnet1",
      "subnets": "192.168.43.0/24",
      "vlanID": 43,
      "mtu": 1500,
      "netAttachDefName": "aaa/localnet1"
    }
