---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: pg-credentials
      key: POSTGRES_USER
    passwordSecret:
      name: pg-credentials
      key: POSTGRES_PASSWORD
