---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql-keycloak
    app.kubernetes.io/version: '17'
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: keycloak
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:17
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
          envFrom:
            - secretRef:
                name: pg-credentials
      volumes:
        - name: cache-volume
          emptyDir: {}
