apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  selector:
    matchLabels:
      app: nginx2
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nginx
          image: registry.access.redhat.com/ubi9/ubi-micro
          resources:
            requests:
              cpu: "10m"
              memory: 64Mi
            limits:
              cpu: "100m"
              memory: 128Mi
          command: ['sh', '-c', 'while true; do echo "tick" && sleep 60; done']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
