apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
