apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
  namespace: vault
spec:
  vaultAuthRef: vaultauth-webapp
  type: kv-v2
  mount: secret
  path: webapp/config
  destination:
    name: secretkv
    create: true
    transformation:
      excludes:
        - .*
      templates:
        USER:
          text: '{{- get .Secrets "username" -}}'
        PASSWORD:
          text: '{{- get .Secrets "password" -}}'
  refreshAfter: 30s
