apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-app-policies
policyDefaults:
  namespace: policies
  remediationAction: enforce
policies:
  - name: app-nginx
    manifests:
      - path: namespace.yaml
      - path: cm-static-content.yaml
      - path: deployment.yaml
      - path: service.yaml
      - path: route.yaml
