apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: debug-config
    options:
      disableNameSuffixHash: true
    files:
      - bootstrap.conf

patchesStrategicMerge:
  - statefulset-debug.yaml
