kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: tools
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '1.0'
      annotations:
        version: '1.0'
      #from:
      #  kind: DockerImage
      #  name: 'image-registry.openshift-image-registry.svc:5000/cicd-image-streams/tools'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Local
