apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
- name: nginx
  newName: nginxinc/nginx-unprivileged
  newTag: stable

patches:
- path: patch-deployment-ports.yaml
