apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Advanced Cluster Management for Kubernetes"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    openshift.io/cluster-monitoring: 'true'
