apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  namespace: advanced-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  installPlanApproval: Automatic
  name: advanced-cluster-management
