apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  namespace: microshift
  name: nginx
spec:
  workload:
    manifests:
      - apiVersion: v1
        kind: Namespace
        metadata:
          name: nginx
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: nginx
          name: nginx
          labels:
            app: nginx
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: nginxinc/nginx-unprivileged:stable
                  ports:
                    - name: http
                      containerPort: 8080
      - apiVersion: v1
        kind: Service
        metadata:
          name: nginx
          namespace: nginx
        spec:
          selector:
            app: nginx
          ports:
            - port: 8080
              targetPort: http
          type: LoadBalancer
