apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: aaa
  name: openjdk-8
spec:
  selector:
    matchLabels:
      app: openjdk-8
  replicas: 1
  template:
    metadata:
      labels:
        app: openjdk-8
    spec:
      containers:
        - name: openjdk-8
          image: registry.redhat.io/ubi8/openjdk-8-runtime
          command:
            - sleep
            - infinity
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 2000m
              memory: 4Gi
