apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-logging
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-logging
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: day2/logging/resources/overlays/stable-6.1
    repoURL: 'https://github.com/aushacker/os-tools.git'
    targetRevision: HEAD
