apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec
  labels:
    app.kubernetes.io/name: sec-base
spec:
  selector:
    matchLabels:
      app: sec-base
  template:
    metadata:
      labels:
        app: sec-base
    spec:
      serviceAccountName: sa-sec-base
      containers:
        - name: main
          securityContext:
            runAsUser: 0
            privileged: false
            allowPrivilegeEscalation: true
