apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-versions
  namespace: policies
data:
  local-cluster-openshift-logging: stable-6.1
  uri: '{{ (lookup "v1" "DNS" "" "cluster").spec.baseDomain }}'