apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

commonLabels:
  app: nifi-registry

resources:
  - namespace.yaml
  - rb-nonroot.yaml
  - route.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml

images:
  - name: nifi-registry
    newName: docker.io/apache/nifi-registry
  - name: rh-sso
    newName: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8:7.6
