apiVersion: v1
kind: Service
metadata:
  name: nifi-registry
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: nifi-registry-serving-cert
spec:
  selector:
    app: nifi-registry
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
