apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cincinnati-operator
  namespace: default
spec:
  channel: v1
  installPlanApproval: Automatic
  name: cincinnati-operator
  source: cs-redhat-operator-index
  sourceNamespace: openshift-marketplace
