apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-custom-pki
spec:
  dataVolumeTemplates:
    - metadata:
        name: vm-root-volume
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources: {}
  instancetype:
    name: u1.small
  preference:
    name: rhel.9
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: ca-config-disk
              serial: CACONFIG01
      volumes:
        - dataVolume:
            name: vm-root-volume
          name: rootdisk
        - cloudInitNoCloud: 
            userData: |-
              #cloud-config
              user: cloud-user
              password: redhat123
              chpasswd:
                expire: false
              bootcmd:
                # mount the ConfigMap
                - sudo mkdir /mnt/ca-config
                - sudo mount -r /dev/$(lsblk --nodeps -no name,serial | grep CACONFIG01 | cut -f1 -d' ') /mnt/ca-config
                # update the VMs CA trust base
                - sudo cp /mnt/ca-config/ca-bundle.crt /etc/pki/ca-trust/source/anchors
                - sudo update-ca-trust
          name: cloudinitdisk
        - configMap:
            name: user-ca-bundle
          name: ca-config-disk
