apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-infra
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/aushacker/os-tools.git
    targetRevision: HEAD
    path: sandpit/acm/policy-hub
    server: https://kubernetes.default.svc
    namespace: policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
