kind: LocalVolume
apiVersion: local.storage.openshift.io/v1
metadata:
  name: local-volume
  namespace: openshift-local-storage
spec:
  storageClassDevices:
    - devicePaths:
        - /dev/disk/by-id/ata-crucial
      fsType: ext4
      storageClassName: local-storage-blk
      volumeMode: Filesystem
