apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../shared

transformers:
  - |-
    apiVersion: builtin
    kind: PrefixSuffixTransformer
    metadata:
      name: namePrefixer
    prefix: pre-
    fieldSpecs:
      - path: metadata/name
#      - path: spec/selector/app
