kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-provisioner
          env:
            - name: NFS_SERVER
              value: ocp-svc.home.lab
            - name: NFS_PATH
              value: /shares/dynamic
      volumes:
       - name: nfs-volume
         nfs:
           server: ocp-svc.home.lab
           path: /shares/dynamic
