kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-nonroot-v2
subjects:
  - kind: ServiceAccount
    name: sa-mongodb
roleRef:
  kind: Role
  name: use-scc-nonroot-v2
  apiGroup: rbac.authorization.k8s.io
