kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-nonroot-v2
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["nonroot-v2"]
    verbs: ["use"]
