apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: mongodb
    app.kubernetes.io/component: database
    app.openshift.io/runtime: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 3
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      serviceAccountName: sa-mongodb
      securityContext:
        runAsUser: 999
        allowPrivilegeEscalation: false
        runAsNonRoot: true
      initContainers:
        - name: keyfile-config
          image: ubi9-minimal
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - "cp /keyin/keyfile /keyout/keyfile && chmod 0600 /keyout/keyfile"
          volumeMounts:
            - name: keyfile
              mountPath: /keyin
            - name: keyfile-shared
              mountPath: /keyout
      containers:
        - name: mongo
          image: mongodb
          imagePullPolicy: Always
          args:
            - --config
            - /etc/mongo/mongod.conf
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          ports:
            - name: mongodb
              containerPort: 27017
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: config
              mountPath: /etc/mongo
            - name: keyfile-shared
              mountPath: /etc/mongokey
      volumes:
        - name: config
          configMap:
            name: mongod-config
        - name: keyfile
          configMap:
            name: mongod-keyfile
        - name: keyfile-shared
          emptyDir:
            medium: Memory
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: nfs
        resources:
          requests:
            storage: 5Gi
