apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: project-quay
  namespace: openshift-operators
  labels:
    operators.coreos.com/project-quay.openshift-operators: ''
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: project-quay
  source: {{ .Values.subscription.source }}
  sourceNamespace: openshift-marketplace
