apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-security
nameSuffix: -privileged

resources:
  - ../../base
  - service-account.yaml

patches:
  - path: patch-deployment.yaml
