apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec
  labels:
    app.kubernetes.io/name: sec-privileged
spec:
  selector:
    matchLabels:
      app: sec-privileged
  template:
    metadata:
      labels:
        app: sec-privileged
    spec:
      serviceAccountName: sa-sec-privileged
      containers:
        - name: main
          securityContext:
            runAsUser: 0
            privileged: true
            allowPrivilegeEscalation: true
