kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-privileged
subjects:
  - kind: ServiceAccount
    name: sa-sec
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-privileged
