---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - ../../base
  - secret.yaml

images:
  - name: minio
    newName: quay.io/minio/minio
    newTag: latest
