apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: prod-clusters
  namespace: policies
spec:
  clusterSets:
    - prod
  tolerations:
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
