FROM registry.redhat.io/rhel8/go-toolset:1.22 as build

WORKDIR $APP_ROOT/src
COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /opt/app-root/src/web-service-gin /ws-gin

EXPOSE 8080

CMD [ "/ws-gin" ]
