apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: build-secbase
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/ubi:latest

      RUN dnf upgrade -y && \
          dnf install -y --setopt=tsflags=nodocs procps-ng libcap iputils --exclude container-selinux && \
          dnf clean all
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'ubi9:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'secbase:latest'
