apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi8-minimal
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '8.9'
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/ubi-minimal:8.9'
      importPolicy:
        importMode: Legacy
        scheduled: true
      referencePolicy:
        type: Local
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/ubi-minimal:latest'
      importPolicy:
        importMode: Legacy
        scheduled: true
      referencePolicy:
        type: Local