apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ubi9-minimal
spec:
  lookupPolicy:
    local: false
  tags:
    - name: '9.4'
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi9/ubi-minimal:9.4'
      importPolicy:
        importMode: Legacy
        scheduled: true
      referencePolicy:
        type: Local
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi9/ubi-minimal:latest'
      importPolicy:
        importMode: Legacy
        scheduled: true
      referencePolicy:
        type: Local