apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/aushacker/os-tools.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
