apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: openshift-gitops
spec:
  destination:
    namespace: nginx
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: nginx/overlays/unprivileged
    repoURL: 'https://github.com/aushacker/os-tools.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
