apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

resources:
  - ../../base

components:
  - ../../components/azure

replacements:
  - source:
      kind: Secret
      fieldPath: metadata.name
    targets:
      - select:
          kind: ClusterSecretStore
        fieldPaths:
          - spec.provider.azurekv.authSecretRef.clientId.name
          - spec.provider.azurekv.authSecretRef.clientSecret.name
  - source:
      kind: Secret
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ClusterSecretStore
        fieldPaths:
          - spec.provider.azurekv.authSecretRef.clientId.namespace
          - spec.provider.azurekv.authSecretRef.clientSecret.namespace
