apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cm-plugin.yaml
  - service-account.yaml
  - secret-vault-configuration.yaml
  - test-app.yaml

patches:
  - path: patch-argocd.yaml