apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-test-app
spec:
  project: default
  source:
    repoURL: https://github.com/aushacker/os-tools.git
    targetRevision: HEAD
    path: argocd/test-vault
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
