apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-security
nameSuffix: -nonroot

resources:
  - ../../base

images:
  - name: sec
    newName: quay.io/sdavies/sec-base

patches:
  - path: patch-deployment.yaml
