kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  template:
    metadata:
      annotations:
        openshift.io/required-scc: "hostmount-anyuid"
      labels:
        app: nfs-provisioner
    spec:
      containers:
        - name: nfs-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
#          securityContext:
#            allowPrivilegeEscalation: false
#            capabilities:
#              drop:
#                - ALL
          volumeMounts:
            - name: nfs-volume
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-provisioner
            - name: NFS_SERVER
              value: 0.0.0.0
            - name: NFS_PATH
              value: /path
      serviceAccountName: nfs-provisioner
#      securityContext:
#        runAsNonRoot: true
#        seccompProfile:
#          type: RuntimeDefault
      volumes:
       - name: nfs-volume
         nfs:
           server: 0.0.0.0
           path: /path
  strategy:
    type: Recreate
