apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cluster-role.yaml
  - crb-hostmount-anyuid.yaml
  - crb-provisioner.yaml
  - deployment.yaml
  - role.yaml
  - role-binding.yaml
  - service-account.yaml
  - storage-class.yaml
