apiVersion: v1
baseDomain: ocp.lan
compute:
- architecture: amd64
  name: worker
  hyperthreading: Enabled
  replicas: 0
controlPlane:
  architecture: amd64
  name: master
  hyperthreading: Enabled
  replicas: 3
metadata:
  name: lab # Cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14 # OpenShift internal addresses, not visible outside the cluster (overlay network)
      hostPrefix: 23      # Consider 20/21 on baremetal installations
  machineNetwork:
    - cidr: x.x.x.x/24    # External node addresses, visible outside the cluster (underlay network)
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16       # OpenShift internal addresses, not visible outside the cluster (load balancers)
platform:
  none: {}
fips: false               # If true, install needs to be performed from RHEL bastion with FIPS enabled
pullSecret: '{"auths":{ ... }}'
sshKey: 'ssh-ed25519 ...'
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  -----END CERTIFICATE-----
imageDigestSources:
# Cut & paste from working-dir/cluster-resources/idms-oc-mirror.yaml
  - mirrors:
    - <mirrorUrl>:<port>/<repo>/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - <mirrorUrl>:<port>/<repo>/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
