apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-external.yaml
  - service-headless.yaml
  - service-nodeport.yaml
  - route.yaml
  - cm-static-content.yaml

images:
  - name: nginx
    newName: nginxinc/nginx-unprivileged
    newTag: stable
