---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  #generateName: keycloak-
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - keycloak
  upgradeStrategy: Default
