---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  labels:
    operators.coreos.com/rhbk-operator.keycloak: ''
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: stable-v26.2
  installPlanApproval: Manual
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v26.2.5-opr.1
