apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-tools

resources:
  - ../../base

images:
  - name: nginx
    newName: docker.io/nginxinc/nginx-unprivileged
    newTag: stable

patches:
  - path: cm-static-content.yaml
