apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placements
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/aushacker/os-tools.git
    targetRevision: HEAD
    path: sandpit/policy/placements
  destination:
    server: https://kubernetes.default.svc
    namespace: policies
