apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: maven-build
spec:
  params:
    - name: git-url
      description: Repository URL to clone from
      type: string
    - name: git-revision
      default: main
      description: Revision to checkout (branch, tag, sha, ref etc.)
      type: string
    - name: context-dir
      type: string
      description: The context directory within the repository for sources on which we want to execute maven goals
      default: '.'
    - name: image
      type: string
      description: The name (reference) of the image to build.
      default: ""
  tasks:
    - name: fetch
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: unit-test
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch
      params:
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: GOALS
          value:
            - --batch-mode
            - test
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
    - name: package
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - unit-test
      params:
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: GOALS
          value:
            - --batch-mode
            - -DskipTests
            - package
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
  workspaces:
    - name: source
    - name: maven-settings
    - name: maven-local-repo
