apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: maven-build
spec:
  params:
    - name: git-url
      description: Repository URL to clone from
      type: string
    - name: git-revision
      default: main
      description: Revision to checkout (branch, tag, sha, ref etc.)
      type: string
    - name: context-dir
      type: string
      description: The context directory within the repository for sources on which we want to execute maven goals
      default: '.'
    - name: maven-image
      default: 'quay.io/sdavies/maven'
      type: string
    - name: goals-test
      type: array
      description: Maven goals for the unit test task
      default:
        - '--batch-mode'
        - test
    - name: goals-package
      type: array
      description: Maven goals for the package task
      default:
        - --batch-mode
        - -DskipTests
        - package
    - name: image
      type: string
      description: The name (reference) of the image to build.
      default: ""
  tasks:
    - name: fetch
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: unit-test
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/maven/0.3/maven.yaml
      runAfter:
        - fetch
      params:
        - name: MAVEN_IMAGE
          value: $(params.maven-image)
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: GOALS
          value: ["$(params.goals-test[*])"]
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
    - name: package
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/tektoncd/catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/maven/0.3/maven.yaml
      runAfter:
        - unit-test
      params:
        - name: MAVEN_IMAGE
          value: $(params.maven-image)
        - name: CONTEXT_DIR
          value: $(params.context-dir)
        - name: GOALS
          value: ["$(params.goals-package[*])"]
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: maven-settings
        - name: maven-local-repo
          workspace: maven-local-repo
  workspaces:
    - name: source
    - name: maven-settings
    - name: maven-local-repo
