apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
spec:
  channel: latest
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  installPlanApproval: Automatic
  name: openshift-gitops-operator
