apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi
spec:
  secretName: nifi-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  #subject:
  #  organizations:
  #    - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: nifi-nifi.apps.lab.ocp.lan
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - nifi-nifi.apps.lab.ocp.lan
  #uris:
  #  - spiffe://cluster.local/ns/sandbox/sa/example
  #ipAddresses:
  #  - 192.168.0.5
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: keystore
        key: password
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
