FROM registry.access.redhat.com/ubi9-minimal

# --- Original comment---
# Install tools needed for your repo-server to retrieve & decrypt secrets, render manifests
# (e.g. awscli, gpg, sops)
# --- Original comment---
# ubi8 already contains gpg. RH repos do not have awscli.
RUN microdnf upgrade -y && \
    microdnf install -y findutils && \
    microdnf clean all

# Install the AVP plugin (as root so we can copy to /usr/local/bin)
ENV AVP_VERSION=1.18.1
ENV BIN=argocd-vault-plugin
RUN curl -L -o ${BIN} https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 && \
    chmod +x ${BIN} && \
    chown 1000:0 ${BIN} && \
    mv ${BIN} /usr/local/bin

USER 1000
